// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Post struct {
	ID          string
	UserID      string
	Description string
	Price       int32
	Sold        bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SavedPost struct {
	UserID  string
	PostID  string
	SavedAt time.Time
}

type User struct {
	ID        string
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
}
