// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        string
	Username  string
	SavedID   sql.NullString
	PostID    sql.NullString
	CreatedAt time.Time
}

type Post struct {
	ID          string
	UserID      string
	Description string
	Sold        bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
