// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :execresult
INSERT INTO posts(
    user_id, description, price
) VALUES (?, ?, ?)
`

type CreatePostParams struct {
	UserID      string
	Description string
	Price       int32
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost, arg.UserID, arg.Description, arg.Price)
}

const deletePost = `-- name: DeletePost :execresult
DELETE FROM posts WHERE id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePost, id)
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, description, price, sold, created_at, updated_at FROM posts
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.Price,
		&i.Sold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, user_id, description, price, sold, created_at, updated_at FROM posts
ORDER BY updated_at
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.Price,
			&i.Sold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :execresult
UPDATE posts SET description = ?, price = ?, sold = ?
WHERE id=?
`

type UpdatePostParams struct {
	Description string
	Price       int32
	Sold        bool
	ID          string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePost,
		arg.Description,
		arg.Price,
		arg.Sold,
		arg.ID,
	)
}
