// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: saved_post.sql

package db

import (
	"context"
)

const countSavedPostsByPost = `-- name: CountSavedPostsByPost :one
SELECT COUNT(*) FROM saved_posts
WHERE post_id = ?
`

func (q *Queries) CountSavedPostsByPost(ctx context.Context, postID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSavedPostsByPost, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSavedPost = `-- name: CreateSavedPost :exec
INSERT INTO saved_posts(
    user_id, post_id
) VALUES (?, ?)
`

type CreateSavedPostParams struct {
	UserID string
	PostID string
}

func (q *Queries) CreateSavedPost(ctx context.Context, arg CreateSavedPostParams) error {
	_, err := q.db.ExecContext(ctx, createSavedPost, arg.UserID, arg.PostID)
	return err
}

const deleteSavedPost = `-- name: DeleteSavedPost :exec
DELETE FROM saved_posts 
WHERE user_id = ? AND post_id = ?
`

type DeleteSavedPostParams struct {
	UserID string
	PostID string
}

func (q *Queries) DeleteSavedPost(ctx context.Context, arg DeleteSavedPostParams) error {
	_, err := q.db.ExecContext(ctx, deleteSavedPost, arg.UserID, arg.PostID)
	return err
}

const getSavedPostByIds = `-- name: GetSavedPostByIds :one
SELECT user_id, post_id, saved_at FROM saved_posts
WHERE user_id = ? AND post_id = ? LIMIT 1
`

type GetSavedPostByIdsParams struct {
	UserID string
	PostID string
}

func (q *Queries) GetSavedPostByIds(ctx context.Context, arg GetSavedPostByIdsParams) (SavedPost, error) {
	row := q.db.QueryRowContext(ctx, getSavedPostByIds, arg.UserID, arg.PostID)
	var i SavedPost
	err := row.Scan(&i.UserID, &i.PostID, &i.SavedAt)
	return i, err
}

const listSavedPostsByUser = `-- name: ListSavedPostsByUser :many
SELECT user_id, post_id, saved_at FROM saved_posts
WHERE user_id = ?
ORDER BY saved_at DESC
`

func (q *Queries) ListSavedPostsByUser(ctx context.Context, userID string) ([]SavedPost, error) {
	rows, err := q.db.QueryContext(ctx, listSavedPostsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedPost
	for rows.Next() {
		var i SavedPost
		if err := rows.Scan(&i.UserID, &i.PostID, &i.SavedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
